# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: BEMA Podcast Notes
email: adamaverycole+bemapodcastnotes@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A place for my notes as I listen through the BEMA Podcast and capture
  all of the information and details episode by episode.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bema-podcast-notes.github.io" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: G-BZGEW8HB4G
# twitter_username: adamaverycole
github_username: adamaverycole
github_repo: https://github.com/bema-podcast-notes/bema-podcast-notes.github.io/blob/main/

# collections:
#   misc:
#     output: true
#     permalink: /misc/:path/

collections:
  session_1:
    permalink: /session1/:path/
    output: true
  session_2:
    permalink: /session2/:path/
    output: true
  session_3:
    permalink: /session3/:path/
    output: true
  session_4:
    permalink: /session4/:path/
    output: true
  session_5:
    permalink: /session5/:path/
    output: true
  session_6:
    permalink: /session6/:path/
    output: true
  session_7:
    permalink: /session7/:path/
    output: true
  session_8:
    permalink: /session8/:path/
    output: true
  session_9:
    permalink: /session9/:path/
    output: true
  session_10:
    permalink: /session10/:path/
    output: true
  misc_pages:
    permalink: /misc/:path/
    output: true
  # sitemap:
  #   permalink: /sitemapv2.xml
  #   output: true

# Build settings
# + remote_theme: jekyll/minima
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - update_permalinks.py
  - Makefile
  - _scripts/
  - _study-notes/
